filme/urls.py
"""
Para cada página que você for criar do seu site você vai construir 3 coisas:
    - url (link onde a página vai aparecer)
    - view (diz o que vai acontecer quando o usuário acessar determinado link (será puxado algo do banco de dados, será feita uma conta, ele será redirecionado, etc.))
    - template (a parte visual do que será exibido (html))
"""

from django.urls import path, include
from django.urls import reverse_lazy  # modo de passar o reverse dentro do urls.py

# deixaremos de usar função e usaremos classe
# from .views import homepage  # importa a função homepage do arquivo views.py ('.views' porque está na mesma pasta)

# deixaremos de usar função e usaremos classe
# from .views import homefilmes

# importando classes
from .views import Homepage  # importa a classe Homepage do arquivo views.py ('.views' porque está na mesma pasta)
from .views import Homefilmes
from .views import Detalhesfilme
from .views import Pesquisafilme
from .views import Paginaperfil
from .views import Criarconta
from django.contrib.auth import views as auth_view  # para gerenciar login/logout do usuário

app_name = 'filme'  # agora é possível acessar o link de cada página do app filme pelo name='nome da página'

# PASSO 4 - Configurar os links do app filme
urlpatterns = [
#    path('', homepage),  # quando não coloca os parênteses da função ele automaticamente passa o request como parâmetro para função
    path('', Homepage.as_view(), name='homepage'),
#    path('filmes/', homefilmes),  # quando não coloca os parênteses da função ele automaticamente passa o request como parâmetro para função
    path('filmes/', Homefilmes.as_view(), name='homefilmes'),
    path('filmes/<int:pk>', Detalhesfilme.as_view(), name='detalhesfilme'),  # pk = primary key = id, ou seja, vai acrescentar o id de cada filme na barra de endereço do navegador, mostrando dinamicamente, uma página de detalhe para cada filme
    path('pesquisa/', Pesquisafilme.as_view(), name='pesquisafilme'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login'),  # LoginView do Django já vem com formulário 'embutido', a página login.html vai receber esse form
    path('logout/', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),  # LogoutView do Django já vem com formulário 'embutido', a página logout.html vai receber esse form
    path('editarperfil/<int:pk>', Paginaperfil.as_view(), name='editarperfil'),  # pk = primary key = id, ou seja, vai acrescentar o id de cada usuario na barra de endereço do navegador, mostrando dinamicamente, uma página de editar perfil para cada usuário
    path('criarconta/', Criarconta.as_view(), name='criarconta'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name='editarperfil.html', success_url=reverse_lazy('filme:homefilmes')), name='mudarsenha'),
]
# CONEXÃO DE LINKS DINÂMICOS (namespace='filme' -> app_name = 'filme' -> name='homefilmes')

hashflix/urls.py
# urls.py vai definir quais serão os links do site e a relação entre eles

"""
URL configuration for hashflix project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

# urlpatterns - são os links padrão do nosso site
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace='filme')),  # como queremos que o app filme gerencie todos os links do nosso site, vamos deixar vazio '' # namespace='filme' significa que esse path vai incluir todas as urls do app que tem o nome 'filme'
]  # PASSO 2 - adicionamos o link para o app 'filme' (passo 2)
# CONEXÃO DE LINKS DINÂMICOS (namespace='filme' -> app_name = 'filme' -> name='homefilmes')


urlpatterns = urlpatterns + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)  # link onde as imagens do site serão armazenadas

urlpatterns = urlpatterns + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

filme/views.py
"""
Para cada página que você for criar do seu site você vai construir 3 coisas:
    - url (link onde a página vai aparecer)
    - view (diz o que vai acontecer quando o usuário acessar determinado link (será puxado algo do banco de dados, será feita uma conta, ele será redirecionado, etc.))
    - template (a parte visual do que será exibido (html))
"""

"""
Explicando o request: quando você digita no navegador o endereço de um site e aperta enter, você está enviando uma requisição.
Essa requisição pode ser do tipo GET ou do tipo POST.
    GET: quando entra em um site, você está fazendo um GET naquele site, está requisitando as informações do link do site pra exibir no seu navegador.
    POST: quando você preenche um formulário e clica em enviar, está requisitando o envio de informações para o site
"""

# Create your views here.
from django.shortcuts import redirect  # para redirecionar o usuário
from django.contrib.auth.mixins import LoginRequiredMixin  # usado para exigir que o usuário esteja logado para acessar as classes/páginas em que 'LoginRequiredMixin' é passado como primeiro parâmetro
from .forms_personalizados import CriarContaForm
from django.shortcuts import reverse  # para retornar o texto do link
from .forms_personalizados import FormHomepage
from .models import Usuario


# Duas formas de construir um arquivo de views no django:
#     Function-Based Views (FBV) - você tem que criar todos os processos
#     Class-Based Views (CBV) - já trará muita coisa pronta para você


####################################################################################################
# from django.shortcuts import render
# from datetime import date

# Function-Based Views (FBV)
# def homepage(request):
#     ano_atual = {}
#     ano = date.today().year  # 'ano' recebe ano da data de hoje
#     ano_atual['ano'] = ano  # chave 'ano' recebe como valor, a variável 'ano'
#     return render(request, "homepage.html", ano_atual)  # retorna o request e a página 'homepage.html'
####################################################################################################


# TRANSFORMANDO a função homepage() em classe
from django.views.generic import TemplateView  # exibe template
from django.views.generic import FormView


# Class-Based Views (CBV)
class Homepage(FormView):
    template_name = "homepage.html"
    form_class = FormHomepage

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:  # se o usuário está autenticado
            # redireciona para a homefilmes
            return redirect('filme:homefilmes')
        else:
            return super().get(request, *args, **kwargs)  # redireciona para a homepage

    def get_success_url(self):
        email = self.request.POST.get("email")  # pega o texto do email que o usuário insere
        usuarios = Usuario.objects.filter(email=email)  # usuarios recebe o usuário onde o texto da coluna email é igual ao que o usuário acabou de inserir
        if usuarios:  # se existe esse usuário
            return reverse('filme:login')  # vai retornar o texto do link 'filme:login', o link correspondente ao filme login
        else:
            return reverse('filme:criarconta')

####################################################################################################
# from django.shortcuts import render
# from .models import Filme

# 'context' é um dicionário python que você vai passar dentro da sua view como parâmetro para sua página html, isso permite que ao chegar na sua página html, possa usar tags em python para carregar as informações desse dicionário

# Function-Based Views (FBV)
# url - view - html
# def homefilmes(request):
#     context = {}  # dicionário python
#     lista_filmes = Filme.objects.all()  # lista_filmes recebe todos os objetos dentro da tabela Filme
#     context['lista_filmes'] = lista_filmes  # se já existe a chave 'lista_filmes' no dicionário 'context', a chave será substituída, se não existe, será criada'
#     return render(request, "homefilmes.html", context)
####################################################################################################


# TRANSFORMANDO a função homefilmes() em classe
from .models import Filme
from django.views.generic import ListView  # ListView espera que você passe duas informações, o nome do template e o model (o modelo do banco de dados onde tem que pegar a lista (a tabela 'Filme'))


# Class-Based Views (CBV)
class Homefilmes(LoginRequiredMixin, ListView):  # LoginRequiredMixin - Exige login para acessar
    template_name = "homefilmes.html"
    model = Filme  # model recebe a tabela 'Filme'
    # A função passará para 'homefilmes.html' uma lista nomeada "object_list" com o conteúdo da tabela 'Filmes'. 'object_list' é um nome padrão
    # object_list -> lista de itens do modelo


from django.views.generic import DetailView  # para exibir os detalhes de um item


class Detalhesfilme(LoginRequiredMixin, DetailView):  # LoginRequiredMixin - Exige login para acessar
    template_name = "detalhesfilme.html"
    model = Filme
    # variável object -> 1 item do modelo

    def get(self, request, *args, **kwargs):  # redireciona o usuário para a url final
        # descobrir qual filme ele tá acessando
        filme = self.get_object()
        # somar 1 nas visualizações daquele filme
        filme.visualizacoes = filme.visualizacoes + 1
        # salvar
        filme.save()  # salvar a informação no banco de dados

        usuario = request.user
        usuario.filmes_vistos.add(filme)  # essa linha adiciona o usuário atual (id) e o filme acessado no momento (id) em filmes_vistos, no banco de dados

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):  # para não sobreescrever a função que já existe dentro do DetailView, na primeira linha de código da função que estamos criando, escreva a primeira linha assim: "context = super(Detalhesfilme, self).get_context_data(**kwargs)"
        context = super(Detalhesfilme, self).get_context_data(**kwargs)  # essa linha garante que a função que estamos criando não vai sobreescrever a função padrão do DetailView
        # Filtrar a minha tabela de filmes pegando os filmes cuja categoria é igual a categoria do filme da página, ou seja, do object
        # self.get_object()
        filmes_relacionados = Filme.objects.filter(categoria=self.get_object().categoria)[0:5]  # vai retornar uma lista com 5 filmes relacionados
        context["filmes_relacionados"] = filmes_relacionados
        return context  # a lista fica disponível para usar em detalhesfilme.html


class Pesquisafilme(LoginRequiredMixin, ListView):  # LoginRequiredMixin - Exige login para acessar
    template_name = "pesquisa.html"
    model = Filme  # recebe a tabela filme

    # object_list
    def get_queryset(self):
        termo_pesquisa = self.request.GET.get('query')  # pega o texto que foi digitado dentro da barra de pesquisa e passa pra variável 'termo_pesquisa'
        if termo_pesquisa:  # se existe algum texto dentro da barra de pesquisa
            object_list = self.model.objects.filter(titulo__icontains=termo_pesquisa) # filtra a tabela Filme por título everifica se o termo de pesquisa está contido no título dos filmes
            return object_list
        else:
            return None


# LOGIN E LOGOUT não precisam de views aqui porque o Django já tem views padrão para login e logout

from django.views.generic import UpdateView  # a partir da tabela que você passa para ele, ele carrega os campos dessa tabela no formulário para edição
from django.contrib.auth.mixins import UserPassesTestMixin  # para solução do Álvaro


class Paginaperfil(LoginRequiredMixin, UserPassesTestMixin, UpdateView):  # LoginRequiredMixin - Exige login para acessar
    template_name = "editarperfil.html"
    model = Usuario  # tabela Usuário do banco
    fields = ['first_name', 'last_name', 'email']  # campos que permitiremos editar

    # solução do Álvaro para evitar que um usuário possa modificar o perfil de outro passando o id na barra de endereço
    def test_func(self):
        usuario = self.get_object()
        return self.request.user == usuario

    def get_success_url(self):
        return reverse('filme:homefilmes')  # vai retornar o texto do link 'filme:homefilmes', o link correspondente ao filme homefilmes


from django.views.generic import FormView  # view que por padrão passa uma variável form para nosso html


class Criarconta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

    # como o formulário está criando um item no banco de dados
    def form_valid(self, form):  # função que verifica se todos os campos foram preenchidos corretamente
        form.save()  # salva o formulário no banco de dados
        return super().form_valid(form)

    # essa função é obrigatória
    def get_success_url(self):  # diz o que acontecerá se o formulário for bem sucedido
        return reverse('filme:login')  # vai retornar o texto do link 'filme:login', o link correspondente ao filme login

filme/templates/criarconta.html
{% extends 'base.html' %}
{% load static %} <!-- carrega a pasta static -->
{% load crispy_forms_tags %} <!-- carrega o crispy para poder utilizar na página -->

            {% block titulo %}
                Criar Conta
            {% endblock %}

        {% block head %}
            <style>
                .form-text {
                    color: grey;
                }
            </style> <!-- define a cor do texto de informação sobre os campos -->
        {% endblock %}


        {% block content %}
            <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
                <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
                    <form method="post"> <!-- usar o csrf_token -->
                       {% csrf_token %} <!-- ATENÇÃO! É obrigatório passar csrf_token dentro de uma tag python após abrir um form com método POST no django -->
                        <fieldset class="form-group bg-red-600 bg-opacity-75 md:bg-opacity-10 py-5 px-5"> <!-- bg-red-600 bg-opacity-75 md:bg-opacity-10 --> <!-- https://v2.tailwindcss.com/docs/background-opacity -->
                            <legend class="border-bottom mb-4">Crie uma conta para continuar</legend>
                            {{ form|crispy }} <!-- 'formulário|crispy para ativar o crispy e deixar o formulário mais bonito -->
                        </fieldset>
                        <button class="bg-red-600 py-1 px-3 text-white w-full md:text-lg rounded-md" type="submit">Criar Conta</button>
                    </form>
                </div>
            </header>

            <!-- Rodapé -->
            <footer class=" px-5 py-10 ">
                <ul class="flex justify-between items-center">

                    <li>&copy; 2024</li>
                    <li> Feito com Python (Django)</li>
                    <li>Hashtag</li>
                </ul>
            </footer>

        {% endblock %}

filme/templates/detalhesfilme.html
{% extends 'base.html' %}
{% load static %}

            {% block titulo %}
                Home Filmes Hashflix
            {% endblock %}

        {% block content %}
            <main class='bg-primary_black min-h-screen w-full'>

                <!-- primeira sessão - o filme em destaque-->
                <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.thumb_link }}');"> <!-- object.thumb.url = thumb de cada filme -->
                <!-- <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.thumb.url }}');"> --> <!-- object.thumb.url = thumb de cada filme -->
                    <div class="bg-gray-800 bg-opacity-50 px-3"> <!-- bg-gray-800 bg-opacity-50 = fundo do texto -->
                        <h2 class="text-6xl font-semibold text-white my-4">
                            {{ object.titulo }} <!-- título de cada filme -->
                        </h2>
                        <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                            {{ object.descricao|slice:":50" }}... <!-- descrição de cada filme limitada a 50 caracteres -->
                        </p>
                        <div class="flex my-4">
                            <a href="{{ object.episodios.first.video }}"> <!-- link do vídeo do primeiro episódio -->
                                <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                                    <ion-icon name="play" class="text-2xl"></ion-icon>
                                    <span class="ml-3 font-medium">
                                        Play
                                    </span>
                                </button>
                            </a>
                        </div>
                    </div>
                </section>

                <!-- segunda sessão - descrição e episódios -->
                <section class='bg-primary_black flex justify-center py-10'>
                    <div class="p-8 w-10/12 relative" >
                        <h2 class="text-gray-200 text-3xl font-medium">
                            Descrição
                        </h2>
                        <div class="flex justify-left  items-center min-w-full  movie_lis">
                            <p class="text-gray-100 text-lg">
                                {{ object.descricao }} <!-- descrição completa de cada filme -->
                                <br>
                                Visualizações: {{ object.visualizacoes }} <!-- visualizações de cada filme -->
                            </p>
                        </div>

                        <div style='margin-top:2rem;margin-bottom:2rem;'>
                            <h2 class="text-gray-200 text-3xl font-medium">
                                Episódios

                            </h2>
                            {% for episodio in object.episodios.all %} <!-- retorna todos os episódios do filme -->
                                <h3 class='text-lg'>
                                    <a href="{{ episodio.video }}">
                                        <p>Episódio {{ forloop.counter }}: {{ episodio.titulo }}</p> <!-- mostra o número e o título de cada episódio -->
                                    </a>
                                </h3>
                            {% endfor %}

                        </div>

                    </div>
                </section>

                <!-- terceira sessão - relacionados -->
                <section class='bg-primary_black flex justify-center py-10'>
                    <div class="p-8 w-10/12 relative" >
                        <h2 class="text-gray-200 text-2xl font-medium">
                            Relacionados
                        </h2>
                        <div class="flex flex-wrap items-center min-w-full movie_lis">
                            {% for filme in filmes_relacionados %}
                                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                                    <a href="{% url 'filme:detalhesfilme' filme.pk %}"> <!-- link para página detalhesfilme de cada filme relacionado, passando o id como parâmetro (filme.pk)-->
                                            <img src="{{ filme.thumb_link }}" class="object-cover w-full h-full " alt=""> <!-- thumb de cada filme relacionado com o filme em destaque -->
                                            <!-- <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt=""> --> <!-- thumb de cada filme relacionado com o filme em destaque -->
                                    </a>
                                </div>

                                Id: {{ filme.pk }} <!-- id de cada filme relacionado com o filme em destaque -->

                            {% endfor %}
                        </div>
                    </div>
                </section>

            </main>

        {% endblock %}

filme/templates/editarperfil.html
{% extends 'base.html' %}
{% load static %} <!-- carrega a pasta static -->
{% load crispy_forms_tags %} <!-- carrega o crispy para poder utilizar na página -->


            {% block titulo %}
                Editar Perfil
            {% endblock %}

        {% block content %}
            <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
                <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
                    <h2 class="text-2xl">{{ user.username }}</h2>

                    <form method="post">
                        {% csrf_token %}  <!-- ATENÇÃO! É obrigatório passar csrf_token dentro de uma tag python após abrir um form com método POST no django -->
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
                            {{ form|crispy }}
                        </fieldset>
                        <button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Confirmar Edição</button>
                    </form>
                    <small><a href="{% url 'filme:mudarsenha' %}">Quer mudar sua senha?</a></small>
                </div>
            </header>

            <footer class=" px-5 py-10 ">
                <ul class="flex justify-between items-center">

                    <li>&copy; 2024</li>
                    <li> Feito com Python (Django)</li>
                    <li>Hashtag</li>
                </ul>
            </footer>

        {% endblock %}

filme/templates/homepage.html
{% extends 'base.html' %}
{% load static %} <!-- carrega a pasta static -->

            {% block titulo %}
                Home Page Hashflix
            {% endblock %}

        {% block head %}
            <!-- editando apenas 1 item pelo id dele -->
            <style>
                #id_email{
                    width: 100% !important;
                    color: #000000;
                    padding: 10px 10px;
                }
            </style> <!-- personalizando largura, cor do texto e padding -->
        {% endblock %}

        {% block content %}
            <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-black border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix2.jpg' %}');"> <!-- https://tailwindcss.com/docs/background-blend-mode --> <!-- https://tailwindcss.com/docs/border-color -->
                <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col"> <!-- 'flex-col' adiciona os itens um abaixo do outro-->

                    <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
                        Filmes e séries da Hashtag, tudo em um só lugar.
                    </h1>
                    <h3 class="text-xl md:text-xl py-5">
                        Assista onde quiser. Cancele quando quiser.
                    </h3>
                    <h4 class="text-sm md:text-lg pb-3">
                        Quer começar? Coloque seu e-mail abaixo para acessar.
                    </h4>

                    <div class="w-full flex justify-center">
                        <div class="flex justify-center items-center w-11/12 md:w-10/12">

                            <!-- formulário de acesso -->
                            <form method="post" class="w-6/12 justify-center">
                                {% csrf_token %}  <!-- ATENÇÃO! É obrigatório passar csrf_token dentro de uma tag python após abrir um form com método POST no django -->
                                <div class="flex flex-grow items-stretch">
                                    <div class="w-9/12">
                                        {{ form }}
                                    </div>
                                    <div class="w-4/12">
                                        <button class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                                            <span>
                                                Acessar
                                            </span>
                                            <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon> <!-- https://ionic.io/ionicons/usage -->
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>


            </header>

            <!-- primeira sessão -->
            <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
                <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
                    <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                        Enjoy on your TV.
                    </h2>
                    <h5 class="md:text-xl text-lg">
                        Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
                    </h5>
                </div>
                <div class='md:w-1/2 flex justify-center items-center'>
                    <img src="{% static 'images/tv.png' %}" class="w-8/12" alt="">
                </div>
            </section>

            <!-- segunda sessão -->
            <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
                <div class='md:w-1/2 flex justify-center items-center '>
                    <img src="{% static 'images/mobile-0819.jpg' %}" class="w-8/12" alt="">
                </div>

                <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
                    <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                        Download your shows to watch offline.
                    </h2>
                    <h5 class="md:text-xl text-lg">
                        Save your favorites easily and always have something to watch.
                    </h5>
                </div>

            </section>

            <!-- terceira sessão -->
            <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
                <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
                    <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                        Create profiles for kids.
                    </h2>
                    <h5 class="md:text-xl text-lg">
                        Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
                    </h5>
                </div>

                <div class='md:w-1/2 flex justify-center items-center'>
                    <img src="{% static 'images/netflix_kid.png' %}" class="w-8/12" alt="">
                </div>
            </section>
            <footer class=" px-5 py-10 "> <!-- rodapé -->
                <ul class="flex justify-between items-center"> <!-- lista -->
                    <li>&copy; 2024</li>

                    <!-- <li> &copy; {{ ano }} </li> -->
                    <li> Feito com Python (Django)</li>
                    <li>Hashtag</li>
                </ul>
            </footer>

        {% endblock %}

filme/templates/pesquisa.html
{% extends 'base.html' %}
{% load static %} <!-- carrega a pasta static -->

            {% block titulo %}
                Pesquisa de Filmes
            {% endblock %}

        {% block content %}
            <main class='bg-primary_black min-h-screen w-full'>
                <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
                    <div class="p-8 w-10/12 relative" >
                        <h2 class="text-gray-200 text-2xl font-medium">
                            Resultados da Busca
                        </h2>
                        <div class="flex flex-wrap items-center min-w-full movie_lis">
                          {% for filme in object_list %}
                            <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                                <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                  <img src="{{ filme.thumb_link }}" class="object-cover w-full h-full " alt="">
                                  <!-- <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt=""> -->
                                </a>
                            </div>
                          {% endfor %}
                        </div>


                    </div>
                </section>
            </main>
        {% endblock %}