filme/urls.py
"""
Para cada página que você for criar do seu site você vai construir 3 coisas:
    - url (link onde a página vai aparecer)
    - view (diz o que vai acontecer quando o usuário acessar determinado link (será puxado algo do banco de dados, será feita uma conta, ele será redirecionado, etc.))
    - template (a parte visual do que será exibido (html))
"""

from django.urls import path, include
from django.urls import reverse_lazy  # modo de passar o reverse dentro do urls.py

# deixaremos de usar função e usaremos classe
# from .views import homepage  # importa a função homepage do arquivo views.py ('.views' porque está na mesma pasta)

# deixaremos de usar função e usaremos classe
# from .views import homefilmes

# importando classes
from .views import Homepage  # importa a classe Homepage do arquivo views.py ('.views' porque está na mesma pasta)
from .views import Homefilmes
from .views import Detalhesfilme
from .views import Pesquisafilme
from .views import Paginaperfil
from .views import Criarconta
from django.contrib.auth import views as auth_view  # para gerenciar login/logout do usuário

app_name = 'filme'  # agora é possível acessar o link de cada página do app filme pelo name='nome da página'

# PASSO 4 - Configurar os links do app filme
urlpatterns = [
#    path('', homepage),  # quando não coloca os parênteses da função ele automaticamente passa o request como parâmetro para função
    path('', Homepage.as_view(), name='homepage'),
#    path('filmes/', homefilmes),  # quando não coloca os parênteses da função ele automaticamente passa o request como parâmetro para função
    path('filmes/', Homefilmes.as_view(), name='homefilmes'),
    path('filmes/<int:pk>', Detalhesfilme.as_view(), name='detalhesfilme'),  # pk = primary key = id, ou seja, vai acrescentar o id de cada filme na barra de endereço do navegador, mostrando dinamicamente, uma página de detalhe para cada filme
    path('pesquisa/', Pesquisafilme.as_view(), name='pesquisafilme'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login'),  # LoginView do Django já vem com formulário 'embutido', a página login.html vai receber esse form
    path('logout/', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),  # LogoutView do Django já vem com formulário 'embutido', a página logout.html vai receber esse form
    path('editarperfil/<int:pk>', Paginaperfil.as_view(), name='editarperfil'),  # pk = primary key = id, ou seja, vai acrescentar o id de cada usuario na barra de endereço do navegador, mostrando dinamicamente, uma página de editar perfil para cada usuário
    path('criarconta/', Criarconta.as_view(), name='criarconta'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name='editarperfil.html', success_url=reverse_lazy('filme:homefilmes')), name='mudarsenha'),
]
# CONEXÃO DE LINKS DINÂMICOS (namespace='filme' -> app_name = 'filme' -> name='homefilmes')

hashflix/urls.py
# urls.py vai definir quais serão os links do site e a relação entre eles

"""
URL configuration for hashflix project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

# urlpatterns - são os links padrão do nosso site
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace='filme')),  # como queremos que o app filme gerencie todos os links do nosso site, vamos deixar vazio '' # namespace='filme' significa que esse path vai incluir todas as urls do app que tem o nome 'filme'
]  # PASSO 2 - adicionamos o link para o app 'filme' (passo 2)
# CONEXÃO DE LINKS DINÂMICOS (namespace='filme' -> app_name = 'filme' -> name='homefilmes')


urlpatterns = urlpatterns + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)  # link onde as imagens do site serão armazenadas

urlpatterns = urlpatterns + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

templates/base.html
<!DOCTYPE html>
<html lang="en">


    <head>
        <meta charset="UTF-8">
        <title>
            {% block titulo %}

            {% endblock %}
        </title>

        <!-- link do Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> <!-- https://getbootstrap.com/docs/5.3/getting-started/introduction/ -->

        <!-- Tailwind -->
        <script src="https://cdn.tailwindcss.com"></script> <!-- https://tailwindcss.com/docs/installation/play-cdn -->

        {% block head %}

        {% endblock%}


    </head>
    <body class="bg-black text-gray-100 font-primary"> <!-- bg-black = fundo preto -->

        {% include 'navbar.html' %}

        {% block content %}

        {% endblock %}


        <!-- ionicons - framework de ícones -->
        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

        <!-- barra de navegação dinâmica -->
        <!-- se o scroll vertical for maior que 100 (a barra de navegação fica preta com 50% de opacidade)-->
        <!-- se o scroll vertical for maior que o tamanho da tela (a barra de navegação fica invisível)-->
        <script>
            const nav = document.querySelector('nav')

            document.addEventListener("scroll",e=>{
                if(scrollY>100){
                    if(scrollY>window.innerHeight){
                        nav.classList.add('invisible')
                    }
                    else{
                        nav.classList.add('bg-black/50')
                        nav.classList.remove('invisible')
                    }
                }
                else{
                    nav.classList.remove('bg-black/50')
                    nav.classList.remove('invisible')
                }
            })
        </script>
    </body>
</html>

templates/navbar.html
<!-- w-full = largura da página inteira -->
<!-- flex = como se fosse um container de itens -->
<!-- justify-between = distribui os itens em distâncias iguais na página -->
<!-- items-center = centraliza os itens verticalmente -->
<!-- fixed = vai ficar sempre no topo da página -->
<!-- z-50 = para colocar a barra de navegação sobre todas as páginas, as demais terão número menor para ficar atrás -->

{% load static %} <!-- carrega a pasta static com os arquivos de imagem do site -->

<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <div class="w-6/12">
        <a href="/"> <!-- logo é um link para homepage -->
            <img class="5/12" src="{% static 'images/hashflix.png' %}"> <!-- logo do site -->
        </a>
    </div>



    <div class="w-6/12 flex flex-nowrap justify-end">
        {% if user.is_authenticated %}
            <!-- CAMPO DE PESQUISA -->
            <div class="mr-2">
                <form method="get" action="{% url 'filme:pesquisafilme' %}"> <!-- o padrão de pesquisa é com o método get -->
                    <input type="text" class="py-1 px-2 rounded-md text-black" name="query" value="{{ request.GET.query }}" placeholder="Pesquisar..."> <!-- name=query aqui definimos que a palavra que aparecerá na barra de endereço é query --> <!-- value="{{ request.GET.query }}" pega o texto que o usuário digitou na barra de pesquisa e mantém escrito na barra -->
                    <input type="submit" value=""> <!-- submit é como um botão que envia informação -->
                </form>
            </div>
        {% endif %}


        <div class="mr-2">
            {% if user.is_authenticated %}
                <a href="{% url 'filme:logout' %}"> <!-- faz logout do usuário -->
                    <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                        Sair
                    </button> <!-- https://v1.tailwindcss.com/components/buttons -->
                </a>
            {% else %}
                <a href="{% url 'filme:login' %}">
                    <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                        Login
                    </button> <!-- https://v1.tailwindcss.com/components/buttons -->
                </a>
            {% endif %}
        </div>


        {% if user.is_authenticated %}
            <div class="mr-2">
                <a href="{% url 'filme:editarperfil' user.pk %}">  <!-- acessa a página de editar perfil passando como parâmetro o id do usuário atual ('request.user.pk' ou 'request.user.id')-->
                    <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                        Editar Perfil
                    </button> <!-- https://v1.tailwindcss.com/components/buttons -->
                </a>
            </div>
        {% endif %}

        <!-- Teste Sair -->
        <div class="mr-2">
            <form method="post" action="{% url 'filme:logout' %}">
                {% csrf_token %}
                <button class="bg-red-600 text-white py-1 px-3 rounded-md" type="submit">TESTE SAIR</button>
            </form>
        </div>

    </div>
</nav>